package Main.Configs;

public class Const {
    public static final String SHARE_TABLE = "instruments";
    public static final String SHARE_FIGI = "figi";
    public static final String SHARE_TICKER = "ticker";
    public static final String SHARE_CLASSCODE = "classCode";
    public static final String SHARE_ISIN = "isin";
    public static final String SHARE_LOT = "lot";
    public static final String SHARE_CURRENCY = "currency";
    //    public static final String SHARE_TICKER = "shortEnabledFlag";
//    public static final String SHARE_TICKER = " name = "";
//    public static final String SHARE_TICKER = " exchange = "";
//    public static final String SHARE_TICKER = " ipoDate = "";
//    public static final String SHARE_TICKER = " issueSize = "";
    public static final String SHARE_COUNTRY_OF_RISK = "countryOfRisk";
    public static final String SHARE_COUNTRY_OF_RISK_NAME = "countryOfRiskName";
    public static final String SHARE_SECTOR = "sector";
//    public static final String SHARE_TICKER = " issueSizePlan = "";
//    public static final String SHARE_TICKER = " currencyUN = "";
//    public static final String SHARE_TICKER = " units = "";
//    public static final String SHARE_TICKER = " nano = -1;
//    public static final String SHARE_TICKER = " tradingStatus = "";
//    public static final String SHARE_TICKER = " otcFlag = false;
//    public static final String SHARE_TICKER = " buyAvailableFlag = false;
//    public static final String SHARE_TICKER = " sellAvailableFlag = false;
//    public static final String SHARE_TICKER = " divYieldFlag = false;
//    public static final String SHARE_TICKER = " shareType = "";
//    public static final String SHARE_TICKER = " minPriceIncrement = null;
//    public static final String SHARE_TICKER = " apiTradeAvailable = false;
//    public static final String SHARE_TICKER = " uid = "";
//    public static final String SHARE_TICKER = " realExchange = "";
//    public static final String SHARE_TICKER = " positionUid = "";
//    public static final String SHARE_TICKER = " forIisFlag = false;
//    public static final String SHARE_TICKER = " forQualInvestorFlag = false;
//    public static final String SHARE_TICKER = " weekendFlag = false;
//    public static final String SHARE_TICKER = " blockedTcaFlag = false;
//    public static final String SHARE_TICKER = " first1minCandleDate = "";
//    public static final String SHARE_TICKER = " first1dayCandleDate = "";
}
